### ISSUE TITLE
ModuleNotFoundError: No module named 'sonnet'

### ISSUE THREAD

**Issue by yangjiangeyjg** [siw-engineering/tensor2robot_bcz#3]
/tensor2robot_bcz/tensor2robot/layers/bcz_networks.py", line 24, in <module>
    import sonnet as snt
ModuleNotFoundError: No module named 'sonnet'

Hello, how can I solve this problem?
Thanks!

**Comment by cjpurackal** [comment]
> /tensor2robot_bcz/tensor2robot/layers/bcz_networks.py", line 24, in <module>
> 
>     import sonnet as snt
> 
> ModuleNotFoundError: No module named 'sonnet'
> 
> 
> 
> Hello, how can I solve this problem?
> 
> Thanks!

Try
`pip install sonnet`

**Comment by yangjiangeyjg** [comment]
> > /tensor2robot_bcz/tensor2robot/layers/bcz_networks.py", line 24, in 
> > ```
> > import sonnet as snt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ModuleNotFoundError: No module named 'sonnet'
> > Hello, how can I solve this problem?
> > Thanks!
> 
> Try `pip install sonnet`

Thank you! I have solve it.
